### ISSUE TITLE
Rename repository/django project name

### ISSUE THREAD

**Issue by cc-a** [ImperialCollegeLondon/drunc_ui#112]
We're going to have both the process manager and controller UI's under this application. This makes the current name for the repository and django project `dune_processes` confusing. We should rename the repository and the project directory to reflect this. I suggest `drunc_ui` but could run things by the project team. Obviously take care to coordinate renaming the repository as it will screw up people's git remote configs.

**Comment by AdrianDAlessandro** [comment]
Sounds like `drunc_ui` is the preference.
