### ISSUE TITLE
Summary application tree

### ISSUE THREAD

**Issue by cc-a** [ImperialCollegeLondon/drunc_ui#163]
Requires #160.

A simple visual summary of the hierarchy of running controllers and DAQ processes. The data for this should be accessible via the [ls command](https://github.com/DUNE-DAQ/drunc/wiki/Controller#ls) of the root controller. A simple way of rendering this for the time being would be as nested lists.

- [x] #228
- [x] #229

**Comment by cc-a** [comment]
See #167 for potential web components approach.

**Comment by dalonsoa** [comment]
The application tree will require https://github.com/DUNE-DAQ/drunc/pull/239 to be merged, so it might take some time. In the meantime, we can setup the front end side of things with some dummy data.
