### ISSUE TITLE
Expand Kafka message infrastructure

### ISSUE THREAD

**Issue by cc-a** [ImperialCollegeLondon/drunc_ui#165]
The controller UI requires display of a Kafka message feed in the same manner as the process manager but subscribed to a different topic. The controller UI will need to display messages from the `erskafka-reporting` topic.

We therefore need to expand the current message infrastructure to:
- either store the topic under the `KafkaMessage` model so we can filter messages appropriately for each table OR create separate models for each UI so that messages for each are stored in different database tables.
- Update the Kafka consumer command to listen to the controller topic and save messages appropriately.

One caveat is that with the current development infrastructure messages will not be generated on the `erskafka-reporting` topic. We should discuss how to adapt the existing infrastructure with the project team.

**Comment by jamesturner246** [comment]
Some notes from discussion with the dune team:

* the topic is `erskafka-reporting`, not `command.*.erskafka-reporting` as I did.
* messages from this topic use the same schema as for process manager
* Message timestamps are UTC to everyones knowledge so far, but I still want to be really really sure, so we should bring it up next meeting
* the actual endpoint `erskafka-reporting` is not yet available in the image or the live source, however the schema, timestamps, etc are basically the same as messages from the PM, so can be easily mocked for now.
