### ISSUE TITLE
Message hide button missing

### ISSUE THREAD

**Issue by jamesturner246** [ImperialCollegeLondon/drunc_ui#180]
Describe the bug
Possibly related to the Bootswatch theme change, The message hide (X) button is now missing at the top of the message panel.

To Reproduce
View process manager/

Expected behavior
essage hide (X) button at top right of message panel, which hides msg feed and shows a show messages button near the boot, purge, etc buttons.

Additional context
N/A

**Comment by jamesturner246** [comment]
Actually it's there, just coloured white and hard to see. I saw a darker button variant. I can take this.

**Comment by cvzbynek** [comment]
It doesn't toggle. It just hides the message log, but it won't show it back

**Comment by jamesturner246** [comment]
Hi @cvzbynek. 

You need to click the blue `Show Messages` button to get the message pane back:

![Screenshot from 2024-10-24 15-11-37](https://github.com/user-attachments/assets/16c97c07-088c-4606-992d-9dbcf87880df)

I've fixed this bug in #181, if you would like to test it.

See also #142.

**Comment by cvzbynek** [comment]
Toggle preferable, but ok for now!
