### ISSUE TITLE
Use a Bootswatch theme

### ISSUE THREAD

**Issue by AdrianDAlessandro** [ImperialCollegeLondon/drunc_ui#72]
The in-built Bootstrap theme isn't the best colour scheme. [Bootswatch](https://bootswatch.com) have many free modern web themes that we can use.

See [QwikApp settings](https://github.com/ImperialCollegeLondon/QwikApp_web/blob/main/qwikapp/settings/settings.py#L208C1-L221C2) for how to Include them

**Comment by dalonsoa** [comment]
I vote for `Sandstone`

**Comment by cc-a** [comment]
We have been empowered by the project team to choose something we like.
