### ISSUE TITLE
Select all/deselect all checkbox

### ISSUE THREAD

**Issue by cc-a** [ImperialCollegeLondon/drunc_ui#87]
Requires #86 first.

Once we have checkboxes for each row we can add a checkbox in the column header that checks/dechecks the checkboxes in all table rows. Behaviour as follows:
- if the header checkbox is checked by the user, all row checkboxes should become checked.
- if the header checkbox is unchecked by the user, all row checkboxes should become unchecked.
- if a row checkbox is toggled resulting in all row checkboxes being checked/unchecked, then the header checkbox should become checked/unchecked.
- if a row checkbox is toggled resulting in a mix of checked and unchecked boxes, then the header checkbox should become indeterminate.

Some experimentation required to figure out the best way to do this. Whilst probably doable with htmx, it may be better to use a scripting solution like [hyperscript](https://hyperscript.org/). At least a little bit of scripting will be required as it is needed to set a checkbox to an indeterminate state.

See #85 for reference.

**Comment by dalonsoa** [comment]
This might come handy, as well: https://stackoverflow.com/a/13053561/3778792

**Comment by dalonsoa** [comment]
I do not understand the reason for handling the undetermined state. That column checkbox is a convenience to check/uncheck all boxes. The backend will use the individual boxes to deal with the logic. From the user perspective, I think it should look "unchecked" if there is a mixture of checked/unchecked boxes.
