### ISSUE TITLE
Consider caching process data

### ISSUE THREAD

**Issue by cc-a** [ImperialCollegeLondon/drunc_ui#93]
#89 will update the main process table to poll the server for process data. This in turn will poll the Process Manager for changes to process information. We've been told to expect on the order of 10 simultaneous users. If we assume refreshes every 0.5 seconds that gives 20 calls/second to the server and consequently the Process Manager (assuming users only have one copy of the page open).

Whilst I'm confident that we can handle 20 calls/second by deploying with a capable application server and potentially by using asynchronous views we should check whether that sort of load on the process manager is going to be a problem for them.

If we need to reduce the number of calls to the Process Manager we could create a standalone process that polls the Process Manger and stores the results in the application database. Refresh requests from the UI then only need to hit the database rather than making a gRPC call to the Process Manager. This would reduce the polling rate of the Process Manager to around 2 /second.

A couple of tradeoffs we'd make:
- calls to the Process Manager would not be directly related to a user and may require some sort of dedicated role account authenticated for this purpose.
- in the event that the visibility of different processes would need to vary for different end users, this logic would need to be implemented on our server. Our current steer on this is that it wouldn't be required.

**Comment by cc-a** [comment]
Will consider this later as part of the deployment phase of the work where we will have the opportunity to do some load testing and figure out if this is needed.

**Comment by dalonsoa** [comment]
Your latter comments means that the filtering (see #94) might need to be setup without models at hand to work with, right?

**Comment by cc-a** [comment]
For the time being we're not going to consider this. May review on the basis of deployment load testing or user feedback.
